### ISSUE TITLE
[Query] Where is api.js and utils.js?

### ISSUE THREAD

**Issue by WSeegers** [sveltejs/realworld#27]
Hi there

I apologise if i'm missing something really obvious.

I see utils.js and api.js import in many of the *.svelt files. I understand the the purpose they would serve but for the life of me can't understand how I can't find them.

**Comment by gihrig** [comment]
For the benefit of "posterity"... I was confused by the apparent loss of these files as well.

It turns out, they exist in `./src/node_modules`. The problem is that sometimes search algorithms (and programmers) are "configured" to avoid `node_modules`, or they just don't look in `.src/node_modules`.
